"use client";
import { Dialog } from "@base-ui/react/dialog";
import { CheckCircle2, Download, FileText, Trash2, Upload, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useUtilisateurConnecte } from "@/components/disposition/coquille-administration";
type Document={id:string;type:string;nomFichier:string;estValide:boolean;commentaire:string|null;tailleOctets:number|null;creeLe:string};
const types=["CARTE_IDENTITE","PHOTO_IDENTITE","RELEVE_NOTES","ATTESTATION_INSCRIPTION","LETTRE_MOTIVATION","RECOMMANDATION","AUTRE"];
export function GestionDocuments({candidatureId,reference}:{candidatureId:string;reference:string}){const [ouvert,setOuvert]=useState(false);const [documents,setDocuments]=useState<Document[]>([]);const [type,setType]=useState(types[0]);const [fichier,setFichier]=useState<File|null>(null);const [chargement,setChargement]=useState(false);
  const utilisateur=useUtilisateurConnecte();const peutTeleverser=["SUPER_ADMINISTRATEUR","ADMINISTRATEUR","GESTIONNAIRE_BOURSES","ETUDIANT"].includes(utilisateur.role);const peutVerifier=["SUPER_ADMINISTRATEUR","ADMINISTRATEUR","GESTIONNAIRE_BOURSES"].includes(utilisateur.role);
  async function charger(){const r=await fetch(`/api/candidatures/${candidatureId}/documents`,{cache:"no-store"});const x=await r.json();if(r.ok)setDocuments(x.donnees);else toast.error(x.message)}
  useEffect(()=>{if(ouvert)void charger()},[ouvert]);
  async function televerser(e:React.FormEvent){e.preventDefault();if(!fichier)return toast.error("Choisissez un fichier.");setChargement(true);const data=new FormData();data.set("type",type);data.set("fichier",fichier);const r=await fetch(`/api/candidatures/${candidatureId}/documents`,{method:"POST",body:data});const x=await r.json();setChargement(false);if(!r.ok)return toast.error(x.message);toast.success(x.message);setFichier(null);await charger()}
  async function supprimer(id:string){if(!confirm("Supprimer ce document ?"))return;const r=await fetch(`/api/documents/${id}`,{method:"DELETE"});const x=await r.json();if(!r.ok)return toast.error(x.message);toast.success(x.message);await charger()}
  async function verifier(d:Document){const r=await fetch(`/api/documents/${d.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({estValide:!d.estValide})});const x=await r.json();if(!r.ok)return toast.error(x.message);toast.success(x.message);await charger()}
  return <Dialog.Root open={ouvert} onOpenChange={setOuvert}><Dialog.Trigger className="flex w-full items-center gap-2 rounded-lg px-3 py-2 hover:bg-slate-100"><FileText className="size-4"/>Documents</Dialog.Trigger><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 z-50 bg-slate-950/60"/><Dialog.Viewport className="fixed inset-0 z-50 flex items-end justify-center sm:items-center sm:p-4"><Dialog.Popup className="max-h-[95vh] w-full overflow-y-auto rounded-t-2xl bg-white sm:max-w-3xl sm:rounded-2xl"><div className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><div><Dialog.Title className="font-bold">Documents — {reference}</Dialog.Title><Dialog.Description className="text-sm text-slate-500">Fichiers privés stockés dans Vercel Blob.</Dialog.Description></div><Dialog.Close className="p-2"><X className="size-5"/></Dialog.Close></div>{peutTeleverser&&<form onSubmit={televerser} className="grid gap-3 border-b p-5 sm:grid-cols-[1fr_1fr_auto]"><select value={type} onChange={e=>setType(e.target.value)} className="min-h-11 rounded-xl border px-3">{types.map(t=><option key={t}>{t.replaceAll("_"," ")}</option>)}</select><input accept=".pdf,image/jpeg,image/png,image/webp" type="file" onChange={e=>setFichier(e.target.files?.[0]??null)} className="min-h-11 rounded-xl border p-2 text-sm"/><button disabled={chargement} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 text-white"><Upload className="size-4"/>{chargement?"Envoi…":"Téléverser"}</button></form>}<div className="divide-y">{documents.length===0?<p className="p-8 text-center text-slate-500">Aucun document.</p>:documents.map(d=><div key={d.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><FileText className="size-5 text-blue-700"/><div className="min-w-0 flex-1"><p className="truncate font-medium">{d.nomFichier}</p><p className="text-xs text-slate-500">{d.type.replaceAll("_"," ")} · {d.tailleOctets?`${(d.tailleOctets/1024).toFixed(0)} Ko`:"Taille inconnue"} · {d.estValide?"Validé":"À vérifier"}</p></div><div className="flex gap-2">{peutVerifier&&<button onClick={()=>void verifier(d)} className="rounded-lg border p-2 text-emerald-700" title={d.estValide?"Retirer la validation":"Valider"}><CheckCircle2 className="size-4"/></button>}<a href={`/api/documents/${d.id}/telecharger`} className="rounded-lg border p-2" title="Télécharger"><Download className="size-4"/></a>{utilisateur.role==="SUPER_ADMINISTRATEUR"&&<button onClick={()=>void supprimer(d.id)} className="rounded-lg border p-2 text-red-700" title="Supprimer"><Trash2 className="size-4"/></button>}</div></div>)}</div></Dialog.Popup></Dialog.Viewport></Dialog.Portal></Dialog.Root>}
