"use client";
import Link from "next/link";
import { AlertTriangle, ArrowRight, CalendarClock } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Carte } from "@/components/ui/carte";

type Donnees = { etudiants:number; appels:number; candidatures:number; retenues:number; attributions:number; montantPaye:number; paiementsEnRetard:number; recentes:Array<{id:string;reference:string;statut:string;etudiant:{nom:string;prenom:string};appel:{titre:string}}> ; echeances:Array<{id:string;titre:string;dateCloture:string}> };
export function Statistiques(){
  const [s,setS]=useState<Donnees|null>(null);
  useEffect(()=>{fetch("/api/tableau-de-bord",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.message);setS(x.donnees)}).catch(e=>toast.error(e.message))},[]);
  if(!s)return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6},(_,i)=><div key={i} className="h-28 animate-pulse rounded-2xl bg-slate-200"/>)}</div>;
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Carte titre="Étudiants actifs" valeur={s.etudiants}/><Carte titre="Appels" valeur={s.appels}/><Carte titre="Candidatures" valeur={s.candidatures}/><Carte titre="Candidatures retenues" valeur={s.retenues}/><Carte titre="Bourses actives" valeur={s.attributions}/><Carte titre="Montant payé" valeur={`${s.montantPaye.toLocaleString("fr-FR")} USD`}/></div>
    {s.paiementsEnRetard>0&&<div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertTriangle className="mt-0.5 size-5"/><div><p className="font-semibold">{s.paiementsEnRetard} paiement(s) en retard</p><Link href="/paiements" className="text-sm underline">Ouvrir le suivi des paiements</Link></div></div>}
    <div className="grid gap-6 xl:grid-cols-3"><section className="overflow-hidden rounded-2xl border bg-white xl:col-span-2"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">Candidatures récentes</h2><Link href="/candidatures" className="flex items-center gap-1 text-sm text-blue-700">Tout voir <ArrowRight className="size-4"/></Link></div><div className="overflow-x-auto"><table className="min-w-[640px] w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Référence</th><th className="p-3">Étudiant</th><th className="p-3">Appel</th><th className="p-3">Statut</th></tr></thead><tbody>{s.recentes.map(c=><tr key={c.id} className="border-t"><td className="p-3 font-medium">{c.reference}</td><td className="p-3">{c.etudiant.prenom} {c.etudiant.nom}</td><td className="p-3">{c.appel.titre}</td><td className="p-3">{c.statut.replaceAll("_"," ")}</td></tr>)}</tbody></table></div></section><section className="rounded-2xl border bg-white"><div className="flex items-center gap-2 border-b p-4"><CalendarClock className="size-5 text-blue-700"/><h2 className="font-semibold">Échéances proches</h2></div><div className="divide-y">{s.echeances.length?s.echeances.map(a=><Link href="/appels" key={a.id} className="block p-4 hover:bg-slate-50"><p className="text-sm font-medium">{a.titre}</p><p className="mt-1 text-xs text-slate-500">Clôture le {new Date(a.dateCloture).toLocaleDateString("fr-FR")}</p></Link>):<p className="p-6 text-sm text-slate-500">Aucune échéance dans les 30 prochains jours.</p>}</div></section></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Nouvelle candidature","/candidatures"],["Publier un appel","/appels"],["Saisir un paiement","/paiements"],["Produire un rapport","/rapports"]].map(([lien,href])=><Link key={href+lien} href={href} className="rounded-xl border bg-white p-4 font-medium hover:border-blue-300 hover:text-blue-700">{lien}<ArrowRight className="mt-3 size-4"/></Link>)}</div>
  </div>;
}
