import { NextRequest, NextResponse } from "next/server";
import { erreurApi, exigerAutorisation } from "@/lib/api";
import { calculerNotePonderee, schemaSaisieEvaluation } from "@/lib/calcul-evaluation";
import { prisma } from "@/lib/prisma";

type Contexte = { params: Promise<{ id: string }> };
async function evaluationAccessible(id: string, utilisateur: { id: string; role: string }) {
  return prisma.evaluation.findFirst({ where: { id, ...(utilisateur.role === "EVALUATEUR" ? { evaluateurId: utilisateur.id } : {}) }, include: { candidature: { include: { appel: { include: { criteresEvaluation: true } }, etudiant: { select: { nom: true, prenom: true, matricule: true } } } }, notesCriteres: true } });
}
export async function GET(_: NextRequest, contexte: Contexte) { const acces=await exigerAutorisation("evaluer");if(acces.erreur)return acces.erreur;const evaluation=await evaluationAccessible((await contexte.params).id,acces.session.user);if(!evaluation)return NextResponse.json({succes:false,message:"Évaluation introuvable."},{status:404});return NextResponse.json({succes:true,donnees:evaluation}); }
export async function PATCH(requete: NextRequest, contexte: Contexte) {
  const acces=await exigerAutorisation("evaluer");if(acces.erreur)return acces.erreur;
  try { const id=(await contexte.params).id;const evaluation=await evaluationAccessible(id,acces.session.user);if(!evaluation)return NextResponse.json({succes:false,message:"Évaluation introuvable."},{status:404});if(evaluation.dateEcheance&&evaluation.dateEcheance<new Date())return NextResponse.json({succes:false,message:"La date limite de cette évaluation est dépassée."},{status:409});const analyse=schemaSaisieEvaluation.safeParse(await requete.json());if(!analyse.success)return NextResponse.json({succes:false,message:"La saisie d’évaluation est invalide."},{status:422});const criteres=new Map(evaluation.candidature.appel.criteresEvaluation.map(c=>[c.id,c]));if(analyse.data.notes.length!==criteres.size)return NextResponse.json({succes:false,message:"Tous les critères doivent être notés."},{status:422});const calcul=analyse.data.notes.map(n=>{const c=criteres.get(n.critereId);if(!c||n.note>Number(c.noteMaximale))throw new Error(`Note invalide pour le critère ${c?.libelle??n.critereId}.`);return{note:n.note,noteMaximale:Number(c.noteMaximale),ponderation:Number(c.ponderation)}});const note=calculerNotePonderee(calcul);await prisma.$transaction(async t=>{await t.noteCritereEvaluation.deleteMany({where:{evaluationId:id}});await t.noteCritereEvaluation.createMany({data:analyse.data.notes.map(n=>({...n,evaluationId:id}))});await t.evaluation.update({where:{id},data:{note,decision:analyse.data.decision,commentaire:analyse.data.commentaire,statut:"TERMINEE"}});const moyenne=await t.evaluation.aggregate({where:{candidatureId:evaluation.candidatureId,statut:"TERMINEE"},_avg:{note:true}});await t.candidature.update({where:{id:evaluation.candidatureId},data:{statut:"EN_EVALUATION",scoreFinal:moyenne._avg.note}});await t.journalAudit.create({data:{action:"TERMINER_EVALUATION",entite:"Evaluation",entiteId:id,details:`Note ${note.toFixed(2)}`,utilisateurId:acces.session.user.id}})});return NextResponse.json({succes:true,message:"Évaluation enregistrée.",donnees:{note}})}catch(erreur){return erreurApi(erreur,erreur instanceof Error?erreur.message:"Impossible d’enregistrer l’évaluation.")}
}
